language: node_js

compiler: gcc
sudo: false

jobs:
  include:
    - stage: test
      node_js: "node"
      os: linux
    - stage: platform-test
      node_js: "node"
      os: osx
    - stage: platform-test
      node_js: "7"
      os: linux
    - stage: platform-test
      node_js: "7"
      os: osx
    - stage: platform-test
      node_js: "lts/boron"
      os: linux
    - stage: platform-test
      node_js: "lts/boron"
      os: osx
    - stage: platform-test
      node_js: "lts/argon"
      os: linux
    - stage: platform-test
      node_js: "lts/argon"
      os: osx
    - stage: platform-test
      node_js: "0.12"
      os: linux
    - stage: platform-test
      node_js: "0.10"
      os: linux

install:
  - npm install

script:
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e1e5d538974ea634c1b3
    on_success: change
